feather/config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  resources :courses do
      resources :units
  end
  resources :people

  root 'courses#index'

end

feather/app/models/course.rb
class Course < ActiveRecord::Base
  #has many through
  # has_many :users
  # has_many :people, through: :users
  # validates :title, presence: true, length: { minimum: 5 }

  #has and belongs to many
  has_and_belongs_to_many :people
  has_many :units

  accepts_nested_attributes_for :units, :allow_destroy => true
end

feather/app/models/person.rb
class Person < ActiveRecord::Base
  #has many through
  # has_many :users
  # has_many :courses, through: :users
  
  #has and belongs to many
  has_and_belongs_to_many :courses
end

feather/app/models/unit.rb
class Unit < ActiveRecord::Base
  belongs_to :course
end

feather/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

feather/app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  def index
    @courses = Course.all
  end

  def show
    @course = Course.find(params[:id])
    @courses = Course.all
    @people = Course.find(params[:id]).people
    @array1 = ["collapseOne-l", "collapseTwo-l", "collapseThree-l", "collapseFour-l", "collapseFive-l", "collapseSix-l", "collapseSeven-l"]
    @array2 = ["#collapseOne-l", "#collapseTwo-l", "#collapseThree-l", "#collapseFour-l", "#collapseFive-l", "#collapseSix-l", "#collapseSeven-l"]
    @id = :id
    @welcome = ["American Literature and Composition is a study of the major literary topics and themes across the history of the United States from pre-colonial times to present day. Students will focus on the major literary forms of the emerging nation, analyze the literary themes and trends, and research and compose several papers, speeches, and presentations using representative forms of discourse. ", "Anatomy and physiology is a one year course that involves the structure and function of the human body, as it pertains to how the body systems relate to one another in organization, adaptation, and homeostasis.  This course will involve laboratory activities, projects, dissections, textbook material, models, diagrams, journal writings, and clinical studies.  The material learned in this course can be applied to medical field careers, health and fitness careers, and biological research careers.", "This course assumes that the student has demonstrated a solid foundation in algebra. Topics include the relationships between points, lines, and planes; the axiomatic system; logical thinking and proof-writing; measurement, including area and volume; congruency; similarity; two and three dimensional geometric figures; parallel and perpendicular lines; and the coordinate plane. Instruction in this course is designed for college-bound students." ]
  end

  def new
    @course = Course.new
    @course.units.new
  end

  def edit
    @course = Course.find(params[:id])
  end

  def create
    @course = Course.new(course_params)

    if @course.save
      @courses.units.build
      redirect_to @course
    else
      render 'new'
    end
  end

  def update
    @course = Course.find(params[:id])

    if @course.update(course_params)
      @course.units.build
      redirect_to @course
    else
      render 'edit'
    end
  end

  def destroy
    @course = Course.find(params[:id])
    @course.destroy

    redirect_to courses_path
  end

  private
    def course_params
      params.require(:course).permit(:title, :banner, :headshot, :units)
    end
end

feather/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @course = Course.all
  end
end

feather/app/controllers/people_controller.rb
class PeopleController < ApplicationController
  def index
    @people = Person.all
  end

  def show
    @person = Person.find(params[:id])
  end

  def new
    @person = Person.new
    @courses = Course.all
  end

  def edit
    @person = Person.find(params[:id])
  end

  def create
    @person = Person.new(person_params)

    if @person.save
      @person.courses.build
      redirect_to @person
    else
      render 'new'
    end
  end

  def update
    @person = Person.find(params[:id])

    if @person.update(person_params)
      @person.courses.build
      redirect_to @person
    else
      render 'edit'
    end
  end

  def destroy
    @person = Person.find(params[:id])
    @person.destroy

    redirect_to people_path
  end

  private
    def person_params
      params.require(:person).permit(:firstname, :lastname, :role, { course_ids:[] })
    end


end

feather/app/controllers/units_controller.rb
class UnitsController < ApplicationController
  def index
    @units = Unit.all
  end

  def show
    @unit = Unit.find(params[:id])
  end

  def new
    @unit = Unit.new
  end

  def edit
    @unit = Unit.find(params[:id])
  end


 def create
    @course = Course.find(params[:course_id])
    @unit = @course.units.create(unit_params)
    if @unit.save
      redirect_to course_path(@course)
    else
      render 'new'
    end
  end

  def update
    @unit = Unit.find(params[:id])

    if @unit.update(unit_params)
      # @unit.course.build
      redirect_to @unit
    else
      render 'edit'
    end
  end

  def destroy
    @unit = Unit.find(params[:id])
    @unit.destroy

    redirect_to units_path
  end

  private
    def unit_params
      params.require(:unit).permit(:title, :content)
    end
  
end

feather/app/helpers/application_helper.rb
module ApplicationHelper
end

feather/app/helpers/courses_helper.rb
module CoursesHelper
end

feather/app/helpers/home_helper.rb
module HomeHelper
end

feather/app/helpers/people_helper.rb
module PeopleHelper
end

feather/app/helpers/units_helper.rb
module UnitsHelper
end

feather/app/views/courses/_form.html.erb
<%= form_for @course do |f| %>

     <div class="field">
        <% for unit in Unit.all %>
            <div>
                <%= check_box_tag "course[unit_ids][]", unit.id, @course.units.include?(unit) %>
                <%= unit.title %>
            </div>
        <% end %>
    </div>

  <% if @course.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@course.errors.count, "error") %> prohibited
        this course from being saved:
      </h2>
      <ul>
        <% @course.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :banner %><br>
    <%= f.text_field :banner %>
  </p>
  <p>
    <%= f.label :headshot %><br>
    <%= f.text_field :headshot %>
  </p>


  <p>
    <%= f.submit %>
  </p>

<% end %>

feather/app/views/courses/edit.html.erb
<h1>Editing Course</h1>

<%= render 'form' %>
<%= link_to 'Back', courses_path %>

feather/app/views/courses/index.html.erb
<!DOCTYPE html>
<html>

<head>
  <!-- Meta-Information -->
  <title>Admin Angular Template</title>
  <meta charset="utf-8">
  <meta name="description" content="">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
</head>

<body>
  <!-- Toggle Content -->
  <div class="top-bar">
    <div class="logo">
      <a href="/" title=""> <i class="fa fa-deviantart"></i>Feather</a>
      <div class="menu-options">
        <span class="menu-action"><i></i></span>
      </div>
    </div>
  </div>
  <!-- Top Bar -->
  <header class="side-header light-skin opened-menu">
    <div class="admin-details">
      <span><%= image_tag "rick_astley.jpg" %></span>
      <h3>Rick Astley</h3> <i>Student</i>
      <h5 class="admin-status online">Online</h5>
    </div>
    <div class="menu-scroll">
      <div class="side-menus">
        <nav>
          <ul>
            <li>
              <a href="/" title=""> <i class="fa fa-home"></i> <span>Home</span></a>
            </li>
            <li class="menu-item-has-children"><a href="" title=""><i class="fa fa-book"></i><span>Courses</span></a>
              <ul>
                <% @courses.each do |c| %>
                <li><%= link_to c.title, c %></li>
                <% end %>
              </ul>
            </li>
            <li>
              <a href="#" title=""> <i class="fa fa-calendar"></i> <span>Calendar</span></a>
            </li>
          </ul>
        </nav>
      </div>
    </div>
    <!-- Menu Scroll -->
  </header>
  <!-- Header -->

  <div class="main-content">
    <div class="panel-content">
      <% @courses.each do |c| %>

    <div class="row">
      <div class="col-md-12">
        <div class="profile-sec">
          <div class="profile-sec">
            <div class="profile-banner-sec">
              <!-- <img src="/assets/oceanStrip-d60af651413839947ef0a9aaad1ebb0691c6ffc7b12bcf945ff3c8c8fb0db8f3.jpg" alt="Oceanstrip"> -->
              <%= image_tag c.banner %>
              <span><h1><%= link_to c.title, c %></h1></span>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div>
      <br/>
    </div>
    <% end %>
    <!--<div class="row">
      <div class="col-md-12">
        <div class="profile-sec">
          <div class="profile-sec">
            <div class="profile-banner-sec">
              <img src="/assets/oceanStrip-d60af651413839947ef0a9aaad1ebb0691c6ffc7b12bcf945ff3c8c8fb0db8f3.jpg" alt="Oceanstrip">
              <span><h1>Advanced Design Studio</h1></span>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div>
      <br/>
    </div>
    <div class="row">
      <div class="col-md-12">
        <div class="profile-sec">
          <div class="profile-sec">
            <div class="profile-banner-sec">
              <img src="/assets/oceanStrip-d60af651413839947ef0a9aaad1ebb0691c6ffc7b12bcf945ff3c8c8fb0db8f3.jpg" alt="Oceanstrip">
              <span><h1>Advanced Design Studio</h1></span>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div>
      <br/>
    </div> -->
  </div>
  </div>

            <!-- Main Content -->
            <footer>
              <div class="container">
                <p>© 2016 Feather. Made with <i class="fa fa-heart"></i> </p>
                <ul>
                  <li> <a href="#" title="">Support</a> </li>
                </ul>
              </div>
            </footer>
            <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
          </body>

          </html>

feather/app/views/courses/new.html.erb
<h1>New Course</h1>

<%= render 'form' %>

<%= link_to 'Back', courses_path %>

feather/app/views/courses/show.html.erb
<!DOCTYPE html>
<html>

<head>
  <!-- Meta-Information -->
  <title>Feather Learning</title>
  <meta charset="utf-8">
  <meta name="description" content="">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
</head>

<body>
  <!-- Toggle Content -->
  <div class="top-bar">
    <div class="logo">
      <a href="/" title=""> <i class="fa fa-deviantart"></i>Feather</a>
      <div class="menu-options">
        <span class="menu-action"><i></i></span>
      </div>
    </div>
  </div>
  <!-- Top Bar -->
  <header class="side-header light-skin opened-menu">
    <div class="admin-details">
      <span><%= image_tag "rick_astley.jpg" %></span>
      <h3>Rick Astley</h3> <i>Student</i>
      <h5 class="admin-status online">Online</h5>
    </div>
    <div class="menu-scroll">
      <div class="side-menus">
        <nav>
          <ul>
            <li>
              <a href="/" title=""> <i class="fa fa-home"></i> <span>Home</span></a>
            </li>
            <li class="menu-item-has-children"><a href="" title=""><i class="fa fa-book"></i><span>Courses</span></a>
              <ul>
                <% @courses.each do |c| %>
		<li><%= link_to c.title, c %></li>
                <% end %>
              </ul>
            </li>
            <li>
              <a href="#" title=""> <i class="fa fa-calendar"></i> <span>Calendar</span></a>
            </li>
          </ul>
        </nav>
      </div>
    </div>
    <!-- Menu Scroll -->
  </header>
  <!-- Header -->

  <div class="main-content">
    <div class="panel-content">
      <div class="row">
        <div class="col-md-12">
          <div class="profile-sec">
            <div class="profile-banner-sec">
              <%= image_tag @course.banner %>
            </div>
            <div class="user-bar">
              <div class="user-thumb">
                <%= image_tag @course.headshot %>
              </div>
              <div> <span><h1><%= @course.title %></h1></span> <span><h2></h2></span> <br /><br />
              </div>
            </div>
          </div>
        </div>
      </div>
      <!-- Profile Sec -->
      <div class="row">
        <div class="col-md-12">
          <div class="widget">
            <div class="collapse-sec">
              <div class="widget-title">
                <h3>Welcome!</h3> <span>In this course you will learn the basic principles and concepts necessary to understanding the framework behind this generative lens and fully conceptualize the theories of knowledge created throughout the semester. This course is designed to enable all students to actively participate in an equitable and inclusive learning environment while fostering peer based learning through interdisciplinary approaches to understanding. Course work is designed in the project based learning framework and includes learning objectives outlined in the state standards for cross-cutting concepts.</span>
              </div>
                <div id="accordion11" class="panel-group">
                  <% @course.units.each_with_index do |unit, i| %>
                  <div class="panel panel-default">
                    <div class="panel-heading gray">
                      <h4 class="panel-title"> <a data-target=<%= @array2[i]%> data-parent="#accordion11" data-toggle="collapse" class="accordion-toggle"><%= unit.title %></a></h4> </div>
                      <div class="panel-collapse in" id=<%= @array1[i] %> style="height: auto;">
                        <div class="panel-body"><%= unit.content %></div>
                      </div>
                    </div>
                    <% end %>
                    <!-- <div class="panel panel-default">
                    <div class="panel-heading gray">
                    <h4 class="panel-title">
                    <a data-target="#collapseTwo-l" data-parent="#accordion11" data-toggle="collapse" class="accordion-toggle collapsed"> Collapsible Group Item #2 </a>
                  </h4> </div>
                  <div class="panel-collapse collapse" id="collapseTwo-l" style="height: 0px;">
                  <div class="panel-body"> Here</div>
                </div>
              </div>
              <div class="panel panel-default">
              <div class="panel-heading gray">
              <h4 class="panel-title">
              <a data-target="#collapseTwo-l" data-parent="#accordion3" data-toggle="collapse" class="accordion-toggle collapsed"> Collapsible Group Item #2 </a>
            </h4> </div>
            <div class="panel-collapse collapse" id="collapseTwo-l" style="height: 0px;">
            <div class="panel-body">

            <span> Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod. Brunch
            3 wolf moon tempor, sunt aliqua put a bird on it squid single-origin coffee nulla assumenda shoreditch et.</span> <span>span two</span> </div>
          </div>
        </div> -->
      </div>
    </div>
  </div>
</div>
</div>
</div>
<!-- Panel Content -->
</div>
<!-- Main Content -->
<footer>
  <div class="container">
    <p>© 2016 Feather. Made with <i class="fa fa-heart"></i> </p>
    <ul>
      <li> <a href="#" title="">Support</a> </li>
    </ul>
  </div>
</footer>
<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
</body>

</html>

feather/app/views/courses/show_1.html.erb
<h1><%= @course.title %></h1>
<p>
  <strong>Title:</strong>
  <%= @course.title %>
</p>

<p>
  <strong>Banner:</strong>
  <%= @course.banner %>
</p>
<p>
  <strong>People:</strong>
  <%= @people.name %>
</p>

<p>
  <strong>Units:</strong>
  <% @course.units.each do |unit| %>
  <%= @unit.title %>
  <%= @unit.content %>
</p>



<h2>Add a unit:</h2>
<%= form_for([@course, @course.units.build]) do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to 'Edit', edit_course_path(@course) %> |
<%= link_to 'Destroy', course_path(@course),
              method: :delete,
              data: { confirm: 'Are you sure?' } %>

<%= link_to 'Back', courses_path %>

feather/app/views/courses/show_2.html.erb
<!DOCTYPE html>
<html>

<head>
  <!-- Meta-Information -->
  <title>Admin Angular Template</title>
  <meta charset="utf-8">
  <meta name="description" content="">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>


</head>

<body>
  <!-- Toggle Content -->
  <div class="top-bar">
    <div class="logo">
      <a href="index.html" title=""> <i class="fa fa-deviantart"></i> Feather</a>
      <div class="menu-options"> <span class="menu-action"><i></i></span> </div>
    </div>
    <form class="search-form">
      <input type="text" placeholder="Search Here..." />
      <button type="submit"> <i class="fa fa-search"></i> </button>
    </form>
  </div>
  <!-- Top Bar -->
  <header class="side-header light-skin opened-menu">
    <div class="admin-details"> <span>
                <img src="http://placehold.it/896x932" alt="" />
            </span>
      <h3>John doe</h3> <i>Student</i>
      <h5 class="admin-status online">Online</h5> </div>
    <div class="menu-scroll">
      <div class="side-menus"> <span>MAIN LINKS</span>
        <nav>
          <ul>
            <li>
              <a href="widget.html" title=""> <i class="fa fa-home"></i> <span>Home</a>
                        </li>
                        <li class="menu-item-has-children">
                            <a href="" title="">
                                <i class="fa fa-book"></i>
                                <span>Courses</a>
                            <ul>
                                <li>
                                    <a href="index.html" title="">
                                        <i class="fa fa-circle-o-notch"></i>
                                        <span>Dashboard 1</span> </a>
            </li>
            <li>
              <a href="index2.html" title=""> <i class="fa fa-circle-o-notch"></i> <span>Dashboard 2</span> </a>
            </li>
            <li>
              <a href="index3.html" title=""> <i class="fa fa-circle-o-notch"></i> <span> Dashboard 3</a>
                                </li>
                                <li>
                                    <a href="index4.html" title="">
                                        <i class="fa fa-circle-o-notch"></i>
                                        <span>Dashboard 4</a>
                                </li>
                            </ul>
                        </li>
                        <li>
                            <a href="chart.html" title="">
                                <i class="fa fa-calendar"></i>
                                <span>Calendar</a>
                        </li>
                    </ul>
                </nav>
            </div>
        </div>
        <!-- Menu Scroll -->
    </header>

    <div class="main-content">
        <div class="panel-content">
            <div class="row">
                <div class="col-md-12">
                    <div class="profile-sec">
                        <div class="profile-banner-sec">
                          <img src="<%= @course.banner %>" alt=""/>
                          <!-- <img src="./images/oceanStrip.jpg" alt="" /> -->
                        </div>
            <div class="user-bar">
        <div class="user-thumb"> <img src="./images/davidkhale.jpg" alt="" /> </div>
        <div>
          <span>
          <!-- <h1>name of course</h1> -->
          <h1><%= @course.title %></h1>
          </span> <span><h2>something goes here</h2></span> </div>
    </div>
    </div>
    </div>
    </div>
    <!-- Profile Sec -->
    <div>
      <div class="row">
        <div class="col-md-12">
          <div class="widget">
            <div class="collapse-sec">
              <div class="widget-title">
                <h3>Welcome!</h3> <span>This project-based course introduces students to advanced topics in the design and development of technology for education, including design thinking for educators, service and human-centered design practices and web programming for interactive learning applications. The Advanced Design Studio provides an opportunity for students to build on their earlier coursework in educational technology design and development by working as a member of a project development team. Through supervised collaborative work around a single project, students will assume roles in and work through the various stages of a project's life cycle, from problem framing  to solution prototyping. The course focal point, the studio project, will be defined by student teams early in the semester. This course consists of both seminar and technical lab sessions and focuses on application design for both formal and informal educational settings.</span>                </div>
              <div id="accordion11" class="panel-group">
                <div class="panel panel-default">
                  <div class="panel-heading gray">
                    <h4 class="panel-title"> <a data-target="#collapseOne-l" data-parent="#accordion11" data-toggle="collapse" class="accordion-toggle"> Exploring Design </a></h4> </div>
                  <div class="panel-collapse in" id="collapseOne-l" style="height: auto;">
                    <div class="panel-body"> In this session we will explore the concept of design in its broadest sense by discussing the relationships between design values, theory, practice, processes and materials. We will also consider common challenges to designing and
                      developing educational technology and review a design framework to guide our work in T581.</div>
                  </div>
                </div>
                <div class="panel panel-default">
                  <div class="panel-heading gray">
                    <h4 class="panel-title">
                                          <a data-target="#collapseTwo-l" data-parent="#accordion11" data-toggle="collapse" class="accordion-toggle collapsed"> Collapsible Group Item #2 </a>
                                        </h4> </div>
                  <div class="panel-collapse collapse" id="collapseTwo-l" style="height: 0px;">
                    <div class="panel-body"> Here</div>
                  </div>
                </div>
                <div class="panel panel-default">
                  <div class="panel-heading gray">
                    <h4 class="panel-title">
                                                        <a data-target="#collapseTwo-l" data-parent="#accordion3" data-toggle="collapse" class="accordion-toggle collapsed"> Collapsible Group Item #2 </a>
                                                    </h4> </div>
                  <div class="panel-collapse collapse" id="collapseTwo-l" style="height: 0px;">
                    <div class="panel-body"> Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon tempor,
                      sunt aliqua put a bird on it squid single-origin coffee nulla assumenda shoreditch et. </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    </div>
    </div>
    </div>
    <!-- Panel Content -->
    </div>
    <!-- Main Content -->
    <footer>
      <div class="container">
        <p>© 2016 Feather. Made with <i class="fa fa-heart"></i> </p>
        <ul>
          <li> <a href="#/" title="">Support</a> </li>
        </ul>
      </div>
    </footer>
<%= javascript_include_tag "application", "data-turbolinks-track" => true %>
</body>

</html>

feather/app/views/home/index.html.erb
<h1>Feather Learning</h1>
<p>Find me in app/views/home/index.html.erb</p>

feather/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Feather</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

feather/app/views/people/_form.html.erb
<%= form_for @person do |f| %>

     <div class="field">
        <% for course in Course.all %>
            <div>
                <%= check_box_tag "person[course_ids][]", course.id, @person.courses.include?(course) %>
                <%= course.banner %>
            </div>
        <% end %>
    </div>

  <% if @person.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@person.errors.count, "error") %> prohibited
        this course from being saved:
      </h2>
      <ul>
        <% @person.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :firstname %><br>
    <%= f.text_field :firstname %>
  </p>

  <p>
    <%= f.label :lastname %><br>
    <%= f.text_field :lastname %>
  </p>

  <p>
    <%= f.label :role %><br>
    <%= f.text_field :role %>
  </p>

  <p>
    <%= f.label :courses %><br>
    <%= f.text_field :courses %>
  </p>

  <p>
    <%= f.submit %>
  </p>

<% end %>

feather/app/views/people/edit.html.erb
<h1>Editing Person</h1>

<%= render 'form' %>
<%= link_to 'Back', people_path %>

feather/app/views/people/index.html.erb
<h1>Listing All People</h1>

<table>
  <tr>
    <th>First Name</th>
    <th>Last Name</th>
    <th>Role</th>
  </tr>

  <% @people.each do |person| %>
    <tr>
      <td><%= person.firstname %></td>
      <td><%= person.lastname %></td>
      <td><%= person.role %></td>
      <td><%= link_to 'Show', person_path(person) %></td>
      <td><%= link_to 'Edit', edit_person_path(person) %></td>
      <td><%= link_to 'Destroy', person_path(person),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
    </tr>
  <% end %>
</table>

feather/app/views/people/new.html.erb
<h1>New Person</h1>

<%= render 'form' %>
<table>
<% @courses.each do |course| %>
  <tr>
    <td><%= course.title %></td>
  </tr>
  <% end %>
</table>
<%= link_to 'Back', people_path %>

feather/app/views/people/show.html.erb
<h1><%= @person.firstname %></h1>
<p>
  <strong>first name:</strong>
  <%= @person.firstname %>
</p>

<p>
  <strong>last name:</strong>
  <%= @person.lastname %>
</p>

<p>
  <strong>role:</strong>
  <%= @person.role %>
</p>

<p>
  <strong>Courses:</strong>
  <%= @person.courses.map {|c| c.banner}.join(', ') %>
</p>

<%= link_to 'Edit', edit_person_path(@person) %> |
<%= link_to 'Destroy', person_path(@person),
              method: :delete,
              data: { confirm: 'Are you sure?' } %>

<%= link_to 'Back', people_path %>

feather/app/views/units/_form.html.erb
<%= form_for @unit do |f| %>

   <div class="field">
        <%=collection_select(:unit, :course, Course.all, :id, :banner)%>
    </div>

  <% if @unit.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@unit.errors.count, "error") %> prohibited
        this course from being saved:
      </h2>
      <ul>
        <% @unit.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :content %><br>
    <%= f.text_field :content %>
  </p>


  <p>
    <%= f.submit %>
  </p>

<% end %>

feather/app/views/units/edit.html.erb
<h1>Editing Unit</h1>

<%= render 'form' %>
<%= link_to 'Back', units_path %>

feather/app/views/units/index.html.erb
<h1>Listing All Units</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Content</th>
    <th>Course</th>
  </tr>

  <% @units.each do |unit| %>
    <tr>
      <td><%= unit.title %></td>
      <td><%= unit.content %></td>
      <td><%= link_to 'Show', unit_path(unit) %></td>
      <td><%= link_to 'Edit', edit_unit_path(unit) %></td>
      <td><%= link_to 'Destroy', unit_path(unit),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
    </tr>
  <% end %>
</table>

feather/app/views/units/new.html.erb
<h1>New Unit</h1>

<%= render 'form' %>

<%= link_to 'Back', units_path %>

feather/app/views/units/show.html.erb
<h1><%= @unit.title %></h1>
<p>
  <strong>Content</strong>
  <%= @unit.content %>
</p>


<p>
  <strong>Course:</strong>
</p>

<%= link_to 'Edit', edit_unit_path(@unit) %> |
<%= link_to 'Destroy', unit_path(@unit),
              method: :delete,
              data: { confirm: 'Are you sure?' } %>

<%= link_to 'Back', units_path %>